set GOOGLE_APPLICATION_CREDENTIALS=../../ParticleDatabase-c1b8570cc840.json
set GCLOUD_PROJECT=particledatabase
set PUBSUB_VERIFICATION_TOKEN=PLIRKOQ413FAAS4H2MX5WQ6O
set PUBSUB_TOPIC=testDB
set PUBSUB_SUBSCRIPTION_NAME=writeDB
npm start